### ISSUE TITLE
Dependency issue with version 0.3.7

### ISSUE THREAD

**Issue by bertrand-benoit** [mithril-security/bastionlab#232]
Hello, it seems there is a dependency issue, it is not possible to install bastionlab (at least for version 0.3.7) with **[poetry](https://python-poetry.org/)** tool (and python 3.10); to reproduce it very quickly, create an empty directory and execute:
```
poetry init -n
poetry add bastionlab

```

Error:
```
  at ~/.local/lib/python3.10/site-packages/poetry/mixology/incompatibility.py:114 in __str__
      110│ 
      111│     def __str__(self) -> str:
      112│         if isinstance(self._cause, DependencyCause):
      113│             print(f'{self._terms=}')
    → 114│             assert len(self._terms) == 2
      115│ 
      116│             depender = self._terms[0]
      117│             dependee = self._terms[1]
      118│             assert depender.is_positive()
```

The corresponding terms is/are: `[<Term bastionlab>] `

**Comment by kbamponsem** [comment]
Hello @bertrand-benoit,

I quickly tried replicating the error you had when adding bastionlab to a sample project and initially, I got the same error. 

I followed the GitHub conversation below and saw that it was a dependency issue with pillow which is somehow related to the pip version. 

[Poetry GitHub Conversation]
https://github.com/python-poetry/poetry/issues/7177

[Solution]
Upgrade your pip to 22+, and it will solve the issue.

Thank you for prompting us on this issue, and we are counting on you in the community.

**Comment by bertrand-benoit** [comment]
Thanks, it fixed the issue.

To be noted that if there are virtualenv/pip OS packages installed, it can conflict with user installed pip version; to remove them: 
```
sudo apt-get remove python3\*-virtualenv python3\*-virtualenv-clone python3\*-virtualenvwrapper virtualenv virtualenvwrapper python3-typing-extensions python3\*-pip
```

Then in a new shell (to refresh PATH environment variable), and after `pip install -U pip`, it is working like a charm ;)
